title: Paco Troyano
logo: /assets/img/headshot_circle.png
description: >-
  Project Manager & AWS Solutions Arch.
  Seville (Spain)
  Skills
  Project Mngmt   [####]
  Service Mngmt   [####]
  Team Leader     [####]
  AWS Sol. Arc.   [### ]
  AWS Sysops      [##  ]
  AWS Devops      [##  ]
    HTML          [#   ]
    CSS           [#   ]
    Javascript    [#   ]
    Python        [#   ]
    React         [#   ]

#  Languages
#  Spanish (100%)
#  English (90%)
email: pacogonzalez@gmail.com
twitter_username: galfordss
show_downloads: false
theme: jekyll-theme-minimal
