title: Paco Troyano
logo: /assets/img/headshot_circle.png
email: pacogonzalez@gmail.com
description: Project Manager & AWS Solutions Architect
Seville (Spain)
https://www.linkedin.com/in/franciscogonzaleztroyano/
Skills
Project Management       [###########]
Service Management       [###########]
Team Leadership          [###########]
AWS Solutions Architect  [########## ]
AWS Sysops               [#########  ]
AWS Devops               [#######    ]
HTML                 [#######    ]
CSS                  [#######    ]
Javascript           [#####      ]
Python               [#######    ]
React                [#####      ]
Languages
Spanish (100%)
English (90%)


show_downloads: false
theme: jekyll-theme-minimal
