title: Paco Troyano
logo: /assets/img/headshot_circle.png
description: Project Manager & AWS Solutions Arch. Seville (Spain)
email: pacogonzalez@gmail.com
twitter_username: galfordss
show_downloads: false
theme: jekyll-theme-minimal
