title: Paco Troyano
logo: /assets/img/headshot_circle.png
description: Project Manager & AWS Cloud Architech Seville (Spain)
[Publication](https://www.mdpi.com/1424-8220/22/11/4240)
show_downloads: false
theme: jekyll-theme-minimal
