title: Paco Troyano
logo: /assets/img/headshot_circle.png
description: Project Manager & AWS Solutions Architect

description: Seville (Spain)
description: pacogonzalez@gmail.com
description: https://www.linkedin.com/in/franciscogonzaleztroyano/

description: Skills
description: Project Management       [###########]
description: Service Management       [###########]
description: Team Leadership          [###########]
description: AWS Solutions Architect  [########## ]
description: AWS Sysops               [#########  ]
description: AWS Devops               [#######    ]
description:   - HTML                 [#######    ]
description:   - CSS                  [#######    ]
description:   - Javascript           [#####      ]
description:   - Python               [#######    ]
description:   - React                [#####      ]

description: Languages
description: Spanish (100%)
description: English (90%)


show_downloads: false
theme: jekyll-theme-minimal
